### ISSUE TITLE
[Feature] Custom caching backend

### ISSUE THREAD

**Issue by Edwin-Luijten** [io-da/query#1]
Provide a way to add a caching backend.  

It would be nice to have a global one and/or one per handler.  
If one is provided on the handler level, use that one instead of the global one.

**Comment by marcobrotas** [comment]
Implemented in version **v1.2.0**
The implementation of cache adapters has been detached from the bus. It's now possible to provide a list of cache adapters that implement the _CacheAdapter_ interface.
The bus uses a _MemoryCacheAdapter_ by default.
Further details are explained in the documentation.
